apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ./aws-auth/release.yml
  - ../../modules/cert-manager
  - ../../modules/karpenter
  - ../../modules/karpenter-provisioning
  - ../../modules/alb-controller
  - ./alb-controller/service-account.yaml
patchesStrategicMerge:
  - ./karpenter/patch-release.yaml
  - ./karpenter/patch-provisioning.yaml
  - ./alb-controller/patch-helm.yaml
