apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ./aws-auth/release.yml
  - ../../modules/cert-manager
  - ../../modules/karpenter
#  - ../../modules/karpenter-provisioning
#patchesStrategicMerge:
#  - ./karpenter/patch-release.yaml
