apiVersion: v1
kind: ConfigMap
metadata:
  name: aws-auth
  namespace: kube-system
data:
  mapRoles: |
    - groups:
      - system:bootstrappers
      - system:nodes
      rolearn: arn:aws:iam::234002441930:role/xxx-dev-role-eks-ci-karpenter
      username: system:node:{{EC2PrivateDNSName}}
    - groups:
      - system:bootstrappers
      - system:nodes
      rolearn: arn:aws:iam::234002441930:role/xxx-dev-role-eks-ci-node-group
      username: system:node:{{EC2PrivateDNSName}}
  mapUsers: |
    - userarn: arn:aws:iam::234002441930:user/habac.jacie@atware.asia
      username: jacie
      groups:
        - system:masters
    - userarn: arn:aws:iam::234002441930:user/ngoc.dang@atware.asia
      username: ngoc
      groups:
        - system:masters