---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: karpenter
  namespace: flux-system
spec:
  interval: 5m0s
  path: ./karpenter
  prune: true
  sourceRef:
    kind: GitRepository
    name: main
  targetNamespace: karpenter
