---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: karpenter
  namespace: karpenter
spec:
  chart:
    spec:
      chart: karpenter
      reconcileStrategy: ChartVersion
      sourceRef:
        kind: HelmRepository
        name: karpenter
      version: v0.27.3
  interval: 1m0s
  values:
    replicas: 1
    serviceAccount:
      annotations:
        eks.amazonaws.com/role-arn: "arn:aws:iam::234002441930:role/s-eks-ci-karpenter"
        name: karpenter
    settings:
      aws:
        clusterName: s-eks-ci
        defaultInstanceProfile: KarpenterNodeInstanceProfile-s-eks-ci
        interruptionQueueName: s-eks-ci
