---
apiVersion: v1
kind: Namespace
metadata:
  name: actions-runner-system
---
apiVersion: v1
kind: Secret
metadata:
  name: controller-manager
  namespace: actions-runner-system
type: Opaque
data:
  github_token: Z2hwX1pCMldRbDVSNHR2WmZEUU9Ncmx4Y1Bvb3FOY0JIQjRaQWNKWg==  #TODO: update admin token
---
apiVersion: source.toolkit.fluxcd.io/v1beta2
kind: HelmRepository
metadata:
  name: actions-runner-controller
  namespace: actions-runner-system
spec:
  url: https://actions-runner-controller.github.io/actions-runner-controller
  interval: 10m
---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: actions-runner-controller
  namespace: actions-runner-system
spec:
  chart:
    spec:
      chart: actions-runner-controller
      reconcileStrategy: ChartVersion
      sourceRef:
        kind: HelmRepository
        name: actions-runner-controller
        namespace: actions-runner-system
      version: 0.23.3
  interval: 1m0s
  values:
    githubWebhookServer:
      enabled: true
      fullnameOverride: actions-webhook
      ingress:
        enabled: true
        hosts:
          - paths:
              - path: "/actions-webhook"
                pathType: Exact
        annotations:
          "kubernetes.io/ingress.class": alb-controller
          "alb.ingress.kubernetes.io/scheme": internet-facing
          "alb.ingress.kubernetes.io/target-type": ip
