---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: actions-runner-controller
  namespace: actions-runner-system
spec:
  chart:
    spec:
      chart: actions-runner-controller
      reconcileStrategy: ChartVersion
      sourceRef:
        kind: HelmRepository
        name: actions-runner-controller
        namespace: actions-runner-system
      version: 0.23.3
  interval: 1m0s
  values:
    githubWebhookServer:
      enabled: true
      fullnameOverride: actions-webhook
      ingress:
        enabled: true
        hosts:
          - paths:
              - path: "/actions-webhook"
                pathType: Exact
        annotations:
          "kubernetes.io/ingress.class": alb-controller
          "alb.ingress.kubernetes.io/scheme": internet-facing
          "alb.ingress.kubernetes.io/target-type": ip
