---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: actions-runner-controller
  namespace: actions-runner-system
spec:
  values:
    githubWebhookServer:
        annotations:
          "alb.ingress.kubernetes.io/load-balancer-name": xxx-dev-alb-ci-webhook
          "alb.ingress.kubernetes.io/subnets": subnet-050d4c0e9101c75d8, subnet-062f67eb5ae118bd8
          # prisma access + GitHub Enterprise Server
          #      "alb-controller-controller.ingress.kubernetes.io/inbound-cidrs": 66.159.200.79/32, 137.83.216.7/32, 137.83.216.125/32, 208.127.111.180/32, 52.196.244.72/32, 52.199.110.99/32
