apiVersion: v1
kind: Namespace
metadata:
  name: karpenter
---
apiVersion: source.toolkit.fluxcd.io/v1beta2
kind: HelmRepository
metadata:
  name: karpenter
  namespace: karpenter
spec:
  interval: 1m0s
  type: oci
  url: oci://public.ecr.aws/karpenter
---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: karpenter
  namespace: karpenter
spec:
  interval: 5m
  chart:
    spec:
      chart: karpenter
      sourceRef:
        kind: HelmRepository
        name: karpenter
        namespace: karpenter
      interval: 1m
      version: v0.27.3
  install:
    createNamespace: true
  values:
    replicas: 1
    serviceAccount:
      annotations:
        eks.amazonaws.com/role-arn: "arn:aws:iam::234002441930:role/xxx-dev-role-eks-ci-karpenter-irsa"
        name: karpenter
    settings:
      aws:
        clusterName: xxx-dev-eks-ci
        clusterEndpoint: https://AFFA8B95C64C9A2E1894F50CB25CC993.gr7.ap-northeast-1.eks.amazonaws.com
        defaultInstanceProfile: xxx-dev-role-eks-ci-karpenter
        interruptionQueueName: xxx-dev-queue-eks-ci-karpenter
