apiVersion: v1
kind: Namespace
metadata:
  name: karpenter
---
apiVersion: source.toolkit.fluxcd.io/v1beta2
kind: HelmRepository
metadata:
  name: karpenter
  namespace: karpenter
spec:
  interval: 1m0s
  type: oci
  url: oci://public.ecr.aws/karpenter
---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: karpenter
  namespace: karpenter
spec:
  interval: 5m
  releaseName: karpenter
  chart:
    spec:
      chart: karpenter
      reconcileStrategy: ChartVersion
      sourceRef:
        kind: HelmRepository
        name: karpenter
        namespace: karpenter
      interval: 1m
      version: v0.27.3
  install:
    createNamespace: true
