apiVersion: v1
kind: ServiceAccount
metadata:
  name: loadbalancer-controller
  namespace: kube-system
  annotations:
    eks.amazonaws.com/role-arn: "arn:aws:iam::234002441930:role/eks-ci-alb-controller-role" #TODO: will be created by Terraform
---
apiVersion: source.toolkit.fluxcd.io/v1beta2
kind: HelmRepository
metadata:
  name: eks
  namespace: kube-system
spec:
  interval: 1m0s
  url: https://aws.github.io/eks-charts
