apiVersion: v1
kind: Namespace
metadata:
  name: actions-runner-system
---
apiVersion: v1
kind: Secret
metadata:
  name: controller-manager
  namespace: actions-runner-system
type: Opaque
data:
  github_token: Z2hwX1pCMldRbDVSNHR2WmZEUU9Ncmx4Y1Bvb3FOY0JIQjRaQWNKWg==  #TODO: update admin token
---
apiVersion: source.toolkit.fluxcd.io/v1beta2
kind: HelmRepository
metadata:
  name: actions-runner-controller
  namespace: actions-runner-system
spec:
  url: https://actions-runner-controller.github.io/actions-runner-controller
  interval: 10m