---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: aws-load-balancer-controller
  namespace: kube-system
spec:
  values:
    vpcId: vpc-0585af8f8bae3e4ad
    clusterName: xxx-dev-eks-ci
    region: ap-northeast-1
    serviceAccount:
      create: false
      name: aws-load-balancer-controller