---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: actions-runner-controller
  namespace: actions-runner-system
spec:
  chart:
    spec:
      chart: actions-runner-controller
      reconcileStrategy: ChartVersion
      sourceRef:
        kind: HelmRepository
        name: actions-runner-controller
      version: 0.23.3
  interval: 1m0s
  values:
    githubWebhookServer:
      enabled: true
      fullnameOverride: actions-webhook
      ingress:
        enabled: true
        hosts:
          # TODO: create ALB
          - host: s-eks-ci-alb-webook-228087039.ap-northeast-1.elb.amazonaws.com
            paths:
              - path: "/actions-webhook"
                pathType: Exact
        annotations:
          "kubernetes.io/ingress.class": alb
          "alb.ingress.kubernetes.io/load-balancer-name": s-eks-ci-alb-webook
          "alb.ingress.kubernetes.io/scheme": internet-facing
          # idm-dev-subnet-operation-public-*
          #      "alb.ingress.kubernetes.io/subnets": subnet-055d79119dd61fdb2, subnet-08d5c291b0f8ed0ad
          # prisma access + GitHub Enterprise Server
          #      "alb.ingress.kubernetes.io/inbound-cidrs": 66.159.200.79/32, 137.83.216.7/32, 137.83.216.125/32, 208.127.111.180/32, 52.196.244.72/32, 52.199.110.99/32
          # *.dev.test.businessportal.kddi.com
          #      "alb.ingress.kubernetes.io/certificate-arn": arn:aws:acm:ap-northeast-1:933934743011:certificate/ebe5b5c0-df94-4c4c-baf2-d67185451efb
          "alb.ingress.kubernetes.io/target-type": ip
