apiVersion: v1
kind: ConfigMap
metadata:
  name: aws-auth
  namespace: kube-system
data:
  # TODO: add involved users
  mapUsers: |
    - userarn: arn:aws:iam::234002441930:user/habac.jacie@atware.asia
      username: jacie
      groups:
        - system:masters